### ISSUE TITLE
Files of the Odroid U3 head and Odroid XU4 head

### ISSUE THREAD

**Issue by show0k** [poppy-project/Poppy-minimal-head-design#12]
Did you overwrite the Odroid U3 version of the head with the one for Odroid XU4 ? 
It should have been great to do a tag at least, or even if is not in the git style make a new file.

Where can we found STL files for this design ? It seems that poppy-humanoid and poppy-torso releases contain old head version.

**Comment by matthieu-lapeyre** [comment]
The 1.0.1 release is a version with U3. The one with XU4 always has been in the dev branch of torso and humanoid without release associated...

It will be done with the next merge and yes it should have been done before when we saw the XU4 would stay for a while.
